services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/healthChecker"]
      interval: 30s
      timeout: 10s
      retries: 5
  db_service:
    image: timescale/timescaledb:latest-pg17
    # image: postgres:17.4
    environment:
      - POSTGRES_USER=steamlens
      - POSTGRES_PASSWORD=steamlens
      - POSTGRES_DB=timescaledb
    ports:
      - "5432:5432"
    # expose:
    #   - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steamlens"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  timescaledb_data: