# 1 - Download & Install Python 3
FROM python:3.12-slim-bullseye

# setup linux os packages

# 2 - Create Virtual Environment
# 3 - Install Python Packages - `pip install <package-name>`
# 4 - FastAPI Hello World


# Create a virtual environment
RUN python -m venv /opt/venv

# Set the virtual environment as the current location
ENV PATH=/opt/venv/bin:$PATH

# Upgrade pip
RUN pip install --upgrade pip

# Set Python-related environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install os dependencies for our mini vm
RUN apt-get update && apt-get install -y \
    # for postgres
    libpq-dev \
    # for Pillow
    libjpeg-dev \
    # for CairoSVG
    libcairo2 \
    # other
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Create the mini vm's code directory
RUN mkdir -p /code

# Set the working directory to that same code directory
WORKDIR /code

# Copy the requirements file into the container
COPY requirements.txt /tmp/requirements.txt

# copy the project code and migration files into the container's working directory
COPY ./src /code
COPY ./alembic.ini /code/alembic.ini
COPY ./alembic /code/alembic

# Install the Python project requirements
RUN pip install -r /tmp/requirements.txt


# make the bash script executable
COPY ./boot/docker-run.sh /opt/run.sh
RUN chmod +x /opt/run.sh

# Clean up apt cache to reduce image size
RUN apt-get remove --purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# In production, do not mount code as a volume or use --reload
# Run the FastAPI project via the runtime script
# when the container starts
CMD ["/opt/run.sh"]