name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Type check
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive src/ || true
      - name: Lint
        run: |
          flake8 src/ || true
          black --check src/ || true
      - name: Run tests
        run: |
          PYTHONPATH=${GITHUB_WORKSPACE} pytest -q || true

